// Detailed cooking instructions for each recipe.
// Each entry maps the recipe ID to an object containing the Italian
// instructions (`it`) and the Polish translation (`pl`). These
// instructions include approximate ingredient amounts and step‑by‑step
// preparations. When a user expands a recipe, these instructions will
// be displayed below the ingredient list. The Italian description can
// be pronounced via the Web Speech API by clicking on it.

window.recipeInstructions = {
  1: {
    it: "Taglia il guanciale (circa 150 g) a dadini e rosolalo in una padella senza olio finché sarà croccante. In una ciotola monta 4 tuorli con 50 g di pecorino e una macinata di pepe nero. Cuoci 400 g di spaghetti in acqua salata fino a quando saranno al dente e conserva un mestolo di acqua di cottura. Scola la pasta, uniscila al guanciale e togli la padella dal fuoco. Aggiungi la crema di uova e formaggio mescolando rapidamente e, se necessario, un po’ di acqua di cottura per ottenere una salsa cremosa. Servi con altro pecorino e pepe.",
    pl: "Pokrój guanciale (ok. 150 g) w kostkę i podsmaż na suchej patelni, aż stanie się chrupiący. W misce ubij 4 żółtka z 50 g pecorino i szczyptą świeżo mielonego pieprzu. Ugotuj 400 g spaghetti w osolonej wodzie al dente, zachowując chochlę wody z gotowania. Odcedź makaron, dodaj go do patelni z guanciale i zdejmij z ognia. Dodaj mieszankę jaj i sera, energicznie mieszając; jeśli trzeba, dodaj trochę wody z gotowania, aby sos był kremowy. Podawaj posypane pecorino i pieprzem."
  },
  2: {
    it: "Per preparare la lasagna alla bolognese serve un ragù ricco e una besciamella cremosa. Cuoci un ragù con 500 g di carne macinata, sedano, carota, cipolla, passata di pomodoro e vino rosso. Prepara la besciamella sciogliendo 50 g di burro, aggiungendo 50 g di farina e poi 500 ml di latte caldo; cuoci fino a che si addensa e profuma con noce moscata. Sbollenta 500 g di sfoglie di lasagna se secche. In una teglia imburrata stendi strati alternati di ragù, pasta, besciamella, 200 g di mozzarella a fette e 100 g di Parmigiano grattugiato. Ripeti fino a esaurimento, termina con besciamella e Parmigiano e qualche fiocchetto di burro. Cuoci in forno a 180 °C per 30–40 minuti finché la superficie sarà dorata. Lascia riposare 10 minuti prima di servire.",
    pl: "Aby przygotować klasyczną lasanię, potrzebny jest bogaty sos ragù i kremowy beszamel. Ugotuj ragù z 500 g mielonego mięsa, selera, marchwi, cebuli, passaty pomidorowej i czerwonego wina. Przygotuj beszamel: rozpuść 50 g masła, dodaj 50 g mąki, a następnie stopniowo 500 ml ciepłego mleka; gotuj, aż zgęstnieje, dopraw gałką muszkatołową. Jeśli używasz suchego makaronu, obgotuj 500 g płatów lasagne. W natłuszczonej formie układaj warstwy: ragù, płaty makaronu, beszamel, 200 g mozzarelli w plastrach i 100 g startego parmezanu. Powtarzaj, aż zużyjesz składniki; ostatnią warstwę posmaruj beszamelem, posyp parmezanem i połóż kilka wiórków masła. Piecz w 180 °C 30–40 minut, aż wierzch się zrumieni. Odstaw na 10 minut przed krojeniem."
  },
  3: {
    it: "Per i veri fettuccine Alfredo sciogli 100 g di burro in una grande padella. Cuoci 400 g di fettuccine in abbondante acqua salata e scolale molto al dente, conservando un po’ di acqua di cottura. Trasferisci la pasta nella padella con il burro e aggiungi 150 g di Parmigiano Reggiano grattugiato, mescolando energicamente e incorporando qualche cucchiaio di acqua di cottura per creare una salsa emulsionata. Se preferisci una versione più ricca, puoi aggiungere 100 ml di panna e saltare dei funghi o pezzetti di pollo in padella prima di mantecare. Servi subito con altro Parmigiano.",
    pl: "Do klasycznych fettuccine Alfredo rozpuść 100 g masła na dużej patelni. Ugotuj 400 g makaronu fettuccine w osolonej wodzie i odcedź bardzo al dente, zachowując trochę wody z gotowania. Przełóż makaron na patelnię z masłem, dodaj 150 g startego Parmezanu i energicznie mieszaj, wlewając po łyżce wodę z gotowania, aż powstanie kremowy sos. Jeśli chcesz bardziej sycącą wersję, dodaj 100 ml śmietanki i podsmaż pieczarki lub kawałki kurczaka przed wymieszaniem. Podawaj od razu, posypany dodatkowym Parmezanem."
  },
  4: {
    it: "Per le tagliatelle al ragù prepara un sugo alla bolognese: soffriggi una cipolla, una carota e un gambo di sedano tritati in olio e burro, aggiungi 400 g di carne macinata mista e 50 g di pancetta, rosola bene e sfuma con 100 ml di vino rosso. Unisci 400 ml di passata di pomodoro, un bicchiere di brodo e cuoci lentamente per almeno 1 ora. Cuoci 400 g di tagliatelle all’uovo e scolale al dente. Condiscile con abbondante ragù caldo e completa con Parmigiano grattugiato.",
    pl: "Przygotuj sos ragù: podsmaż na oliwie i maśle posiekaną cebulę, marchewkę i łodygę selera, dodaj 400 g mieszanej mielonej wołowiny i wieprzowiny oraz 50 g pancetty, obsmaż i podlej 100 ml czerwonego wina. Wlej 400 ml passaty pomidorowej, szklankę bulionu i duś co najmniej godzinę. Ugotuj 400 g makaronu tagliatelle i odcedź al dente. Wymieszaj z obfitym sosem ragù i podawaj posypane tartym parmezanem."
  },
  5: {
    it: "Per preparare i bucatini all’Amatriciana taglia 150 g di guanciale a listarelle e fallo rosolare in padella finché il grasso sarà sciolto. Aggiungi un peperoncino e, se vuoi, mezza cipolla tritata. Sfuma con un goccio di vino bianco e unisci 400 g di pomodori pelati schiacciati. Cuoci il sugo per 10–15 minuti. Nel frattempo cuoci 400 g di bucatini in acqua salata. Scola la pasta al dente, saltala nel sugo e completa con 50 g di Pecorino Romano grattugiato e abbondante pepe.",
    pl: "Aby przygotować bucatini all’Amatriciana, pokrój 150 g guanciale w paski i wytop na patelni, aż tłuszcz się wytopi. Dodaj papryczkę chili i, jeśli chcesz, pół posiekanej cebuli. Podlej odrobiną białego wina, a następnie dodaj 400 g rozgniecionych pomidorów pelati. Gotuj sos 10–15 minut. W tym czasie ugotuj 400 g makaronu bucatini w osolonej wodzie. Odcedź al dente, wymieszaj z sosem i posyp 50 g startego pecorino oraz świeżo mielonym pieprzem."
  },
  6: {
    it: "Cuoci 400 g di penne in acqua salata. In una padella soffriggi dolcemente 3 spicchi di aglio tritati con 2 – 3 peperoncini secchi in 3 cucchiai di olio d’oliva. Aggiungi 400 g di pomodori pelati spezzettati, sale e lascia sobbollire per 15 minuti. Scola le penne al dente, versale nel sugo e mescola bene. Completa con prezzemolo tritato e, a piacere, Pecorino.",
    pl: "Ugotuj 400 g makaronu penne w osolonej wodzie. Na patelni delikatnie podsmaż 3 posiekane ząbki czosnku z 2–3 suszonymi papryczkami chili na 3 łyżkach oliwy. Dodaj 400 g drobno pokrojonych pomidorów pelati, posól i duś 15 minut. Odcedź penne al dente, przełóż do sosu i dokładnie wymieszaj. Posyp posiekaną natką pietruszki i ewentualnie startym pecorino."
  },
  7: {
    it: "Per gli spaghetti aglio, olio e peperoncino affetta sottilmente 4 spicchi d’aglio e rosolali in 60 ml di olio extravergine di oliva insieme a un peperoncino spezzettato. Fai attenzione a non bruciare l’aglio. Cuoci 400 g di spaghetti al dente e scolali tenendo da parte un po’ d’acqua di cottura. Versa la pasta nell’olio aromatico, aggiungi qualche cucchiaio di acqua e mescola bene. Completa con prezzemolo tritato e, se piace, Parmigiano.",
    pl: "Do spaghetti aglio, olio e peperoncino cienko pokrój 4 ząbki czosnku i podsmaż je na 60 ml oliwy z oliwek wraz z pokruszoną papryczką chili, uważając, by czosnek się nie przypalił. Ugotuj 400 g spaghetti al dente, odcedź, zachowując trochę wody z gotowania. Dodaj makaron do aromatyzowanej oliwy, dolej kilka łyżek wody i dobrze wymieszaj. Posyp posiekaną natką pietruszki i ewentualnie tartym parmezanem."
  },
  8: {
    it: "La pasta alla Gricia si prepara con pochi ingredienti: 150 g di guanciale, 100 g di Pecorino Romano, pepe nero e 400 g di pasta (spesso rigatoni). Rosola il guanciale a listarelle finché è croccante. Cuoci la pasta in acqua salata; scolala al dente e condiscila con il grasso del guanciale. A fuoco spento aggiungi il Pecorino grattugiato e qualche cucchiaio di acqua di cottura, mescolando energicamente fino a ottenere una salsa cremosa. Servi con altro pepe.",
    pl: "Pasta alla Gricia wymaga tylko kilku składników: 150 g guanciale, 100 g pecorino, świeżo mielony czarny pieprz i 400 g makaronu (najczęściej rigatoni). Podsmaż paski guanciale, aż będą chrupiące. Ugotuj makaron w osolonej wodzie, odcedź al dente i wymieszaj z wytopionym tłuszczem z guanciale. Po zdjęciu z ognia dodaj starty pecorino i kilka łyżek wody z gotowania, energicznie mieszając, aż sos stanie się kremowy. Podawaj z dużą ilością pieprzu."
  },
  9: {
    it: "Per la pasta alla Norma taglia due melanzane a cubetti, salale e lasciale spurgare per 30 minuti. Asciugale e friggile in olio fino a doratura. In un’altra padella prepara un sugo con 400 g di pomodori pelati, 2 spicchi d’aglio, un pizzico di peperoncino e basilico. Cuoci 400 g di pasta (solitamente maccheroni o spaghetti) al dente, scolala e uniscila al sugo. Aggiungi le melanzane fritte e mescola. Servi con ricotta salata grattugiata (circa 100 g) e basilico fresco.",
    pl: "Do pasty alla Norma pokrój dwie bakłażany w kostkę, posól i odstaw na 30 minut, by puściły sok. Osusz je i usmaż na oliwie, aż będą złote. W osobnym garnku przygotuj sos z 400 g pomidorów pelati, 2 ząbków czosnku, szczypty chili i bazylii. Ugotuj 400 g makaronu (najczęściej penne lub spaghetti) al dente, odcedź i połącz z sosem. Dodaj usmażone bakłażany i wymieszaj. Podawaj posypane ok. 100 g tartej ricotty salaty lub pecorino oraz świeżą bazylią."
  },
  10: {
    it: "Per il pesto genovese pesta in un mortaio 60 g di foglie di basilico, 30 g di pinoli, 2 spicchi d’aglio e un pizzico di sale grosso. Aggiungi 50 g di Parmigiano Reggiano e 30 g di Pecorino Romano grattugiati, quindi versa 100 ml di olio extravergine di oliva a filo, continuando a pestare fino a ottenere una salsa vellutata. Cuoci 400 g di trofie o linguine in acqua salata, scolale al dente e condiscile con il pesto, diluendo con un cucchiaio di acqua di cottura. Servi con altro formaggio.",
    pl: "Przygotuj pesto genueńskie, ucierając w moździerzu 60 g świeżych liści bazylii, 30 g orzeszków piniowych, 2 ząbki czosnku i szczyptę soli gruboziarnistej. Dodaj 50 g startego Parmezanu i 30 g Pecorino, następnie, cały czas ucierając, wlewaj cienkim strumieniem 100 ml oliwy z oliwek, aż sos będzie gładki. Ugotuj 400 g makaronu (trofie, linguine lub spaghetti) w osolonej wodzie, odcedź al dente i wymieszaj z pesto, dodając odrobinę wody z gotowania. Podawaj posypane dodatkowym serem."
  },
  11: {
    it: "Per la pasta al pomodoro trita 2 spicchi d’aglio e falli soffriggere in 3 cucchiai di olio d’oliva. Aggiungi 4 pomodori maturi pelati e tagliati a pezzi (oppure 400 g di polpa) e un po’ di sale. Lascia cuocere a fuoco dolce per 20–25 minuti schiacciando i pomodori fino a ottenere una salsa. Profuma con qualche foglia di basilico. Cuoci 400 g di spaghetti o penne al dente, scolali, trasferiscili nella padella con il sugo e saltali per 2 minuti. Servi con Parmigiano grattugiato e basilico.",
    pl: "Do makaronu al pomodoro posiekaj 2 ząbki czosnku i podsmaż je na 3 łyżkach oliwy. Dodaj 4 obrane i pokrojone pomidory (lub 400 g pomidorowej pulpy) oraz sól. Duś na małym ogniu 20–25 minut, rozgniatając pomidory, aż powstanie sos. Pod koniec dodaj kilka listków bazylii. Ugotuj 400 g spaghetti lub penne al dente, odcedź i przełóż na patelnię z sosem, smaż 2 minuty. Podawaj z tartym parmezanem i bazylią."
  },
  12: {
    it: "La pasta al limone è fresca e veloce. Grattugia la scorza di 2 limoni non trattati e spremine il succo. In una padella sciogli 60 g di burro, aggiungi la scorza e, a piacere, 100 ml di panna. Cuoci 400 g di spaghetti al dente, scolali e falli saltare nel burro al limone. Versa il succo, aggiungi 50 g di Parmigiano grattugiato e mescola bene con un po’ di acqua di cottura. Servi con pepe e altra scorza.",
    pl: "Makaron al limone jest świeży i szybki. Zetrzyj skórkę z 2 niepryskanych cytryn i wyciśnij z nich sok. Na patelni rozpuść 60 g masła, dodaj skórkę i, jeśli chcesz, 100 ml śmietanki. Ugotuj 400 g spaghetti al dente, odcedź i wymieszaj z masłem cytrynowym. Wlej sok, dodaj 50 g tartego parmezanu i dokładnie wymieszaj z odrobiną wody z gotowania. Podawaj z pieprzem i dodatkową skórką cytryny."
  },
  13: {
    it: "Per la pasta con le sarde pulisci 500 g di sarde fresche eliminando testa e lische e tagliale a pezzi. Ammolla 30 g di uvetta in acqua tiepida e tosta 30 g di pinoli. In una padella soffriggi una cipolla tritata con 4 filetti di acciuga e 1 finocchio selvatico affettato, poi aggiungi uvetta e pinoli. Sciogli qualche pistillo di zafferano in poca acqua calda e unisci alle verdure. Aggiungi le sarde e cuoci pochi minuti. Cuoci 400 g di bucatini al dente, scolali e mescolali con il condimento. Servi con pangrattato tostato.",
    pl: "Do makaronu con le sarde oczyść 500 g świeżych sardynek, usuwając głowy i ości, a następnie pokrój je na kawałki. Namocz 30 g rodzynek w ciepłej wodzie i upraż 30 g orzeszków piniowych. Na patelni podsmaż posiekaną cebulę z 4 filetami anchois i pokrojonym koprem włoskim, następnie dodaj rodzynki i orzeszki. Rozpuść szczyptę szafranu w odrobinie ciepłej wody i wlej na patelnię. Dodaj sardynki i smaż kilka minut. Ugotuj 400 g bucatini al dente, odcedź i wymieszaj z sosem. Podawaj posypane prażoną bułką tartą."
  },
  14: {
    it: "Per gli spaghetti alla puttanesca scalda 3 cucchiai di olio con 3 spicchi d’aglio schiacciati e 4 filetti di acciuga fino a scioglierli. Aggiungi un peperoncino, 100 g di olive nere snocciolate e 2 cucchiai di capperi dissalati. Unisci 500 g di pomodori pelati a pezzetti e cuoci per 15 minuti. Cuoci 400 g di spaghetti, scolali al dente e saltali nel sugo. Completa con prezzemolo tritato.",
    pl: "Do spaghetti alla puttanesca rozgrzej 3 łyżki oliwy z 3 zgniecionymi ząbkami czosnku i 4 filetami anchois, aż się rozpuszczą. Dodaj papryczkę chili, 100 g drylowanych czarnych oliwek i 2 łyżki odsączonych kaparów. Dodaj 500 g posiekanych pomidorów pelati i gotuj 15 minut. Ugotuj 400 g spaghetti, odcedź al dente i wymieszaj z sosem. Posyp posiekaną pietruszką."
  },
  15: {
    it: "Per gli spaghetti alla Nerano affetta sottilmente 4 zucchine e friggile in olio fino a dorarle; scolale su carta assorbente. Cuoci 400 g di spaghetti al dente. In una padella scalda un filo d’olio con uno spicchio d’aglio, aggiungi le zucchine fritte e un mestolo di acqua di cottura della pasta; unisci gli spaghetti e manteca con 100 g di Provolone del Monaco grattugiato e 50 g di Parmigiano fino a creare una crema. Termina con foglie di basilico.",
    pl: "Do spaghetti alla Nerano pokrój 4 cukinie na cienkie plastry i usmaż na oleju na złoto; odsącz na papierze. Ugotuj 400 g spaghetti al dente. Na patelni rozgrzej odrobinę oliwy z jednym ząbkiem czosnku, dodaj usmażone cukinie i chochlę wody z gotowania makaronu; dodaj makaron i wymieszaj z 100 g startego sera Provolone del Monaco oraz 50 g parmezanu, aż powstanie kremowy sos. Na końcu dodaj listki bazylii."
  },
  16: {
    it: "Per la pasta alla Boscaiola soffriggi una cipolla tritata con 150 g di pancetta a cubetti in 2 cucchiai di olio. Aggiungi 300 g di funghi porcini o champignon affettati e cuoci finché rilasciano l’acqua. Sfuma con 100 ml di vino bianco, poi unisci 200 ml di panna da cucina e lascia restringere. Cuoci 400 g di pasta (penne o fettuccine), scolala e saltala nel condimento. Servi con prezzemolo tritato e Parmigiano.",
    pl: "Do pasty alla Boscaiola podsmaż posiekaną cebulę z 150 g boczku pokrojonego w kostkę na 2 łyżkach oliwy. Dodaj 300 g pokrojonych grzybów (borowików lub pieczarek) i smaż, aż odparują. Podlej 100 ml białego wina, a następnie wlej 200 ml śmietanki i gotuj, aż sos lekko zgęstnieje. Ugotuj 400 g makaronu (penne lub fettuccine), odcedź i wymieszaj z sosem. Podawaj posypane natką pietruszki i parmezanem."
  },
  17: {
    it: "Per la pasta e fagioli prepara un soffritto con una cipolla, una carota e un gambo di sedano tritati in olio d’oliva. Aggiungi 300 g di fagioli cannellini già lessati, 400 g di pomodori pelati e qualche rametto di rosmarino. Versa 1 litro di brodo e lascia sobbollire 30 minuti; frulla una parte della minestra per renderla cremosa. Aggiungi 200 g di pasta corta (ditalini) e cuoci fino a quando è al dente. Servi con un filo d’olio e Parmigiano.",
    pl: "Do pasty e fagioli przygotuj podsmażkę z posiekanej cebuli, marchewki i selera na oliwie. Dodaj 300 g ugotowanej fasoli cannellini, 400 g pomidorów pelati i kilka gałązek rozmarynu. Wlej 1 l bulionu i gotuj 30 minut; część zupy zmiksuj, aby zagęścić. Dodaj 200 g krótkiego makaronu (ditalini) i gotuj, aż będzie al dente. Podawaj skropione oliwą i posypane parmezanem."
  },
  18: {
    it: "Per la pasta al forno cuoci 500 g di rigatoni o maccheroni molto al dente. Condiscili con 500 g di ragù di carne e 300 ml di besciamella, quindi mescola 300 g di mozzarella a cubetti. Versa metà della pasta condita in una teglia, spolvera con 50 g di Parmigiano e copri con la pasta restante. Completa con altro Parmigiano e qualche fiocchetto di burro. Inforna a 180 °C per 25–30 minuti finché la superficie è dorata.",
    pl: "Do pasty al forno ugotuj 500 g makaronu (rigatoni lub maccheroni) bardzo al dente. Wymieszaj z 500 g sosu ragù i 300 ml beszamelu, dodaj 300 g mozzarelli pokrojonej w kostkę. Połowę makaronu przełóż do naczynia żaroodpornego, posyp 50 g parmezanu, przykryj resztą makaronu. Posyp pozostałym parmezanem i rozłóż kilka kawałków masła. Zapiekaj w 180 °C przez 25–30 minut, aż wierzch się zrumieni."
  },
  19: {
    it: "I tortellini in brodo sono semplici: prepara un buon brodo di carne (manzo o cappone) facendo sobbollire 1,5 litri di acqua con ossa, carne, cipolla, carota e sedano per alcune ore. Filtra il brodo e riportalo a ebollizione. Cuoci 300 g di tortellini freschi nel brodo bollente per 2–3 minuti finché salgono a galla. Servi subito con Parmigiano grattugiato.",
    pl: "Tortellini w rosole są proste: przygotuj dobry bulion z wołowiny lub kapłona, gotując przez kilka godzin 1,5 l wody z kośćmi, mięsem, cebulą, marchewką i selerem. Przecedź bulion i ponownie doprowadź do wrzenia. Gotuj 300 g świeżych tortellini w bulionie przez 2–3 minuty, aż wypłyną. Podawaj od razu, posypane parmezanem."
  },
  20: {
    it: "Per i ravioli ricotta e spinaci porta a bollore abbondante acqua salata. Cuoci 300 g di ravioli ripieni di ricotta e spinaci per 4–5 minuti. Nel frattempo sciogli 100 g di burro in una padella con 8 foglie di salvia fino a profumare. Scola i ravioli con una schiumarola, trasferiscili nella padella e saltali delicatamente. Servi con 50 g di Parmigiano grattugiato.",
    pl: "Ravioli z ricottą i szpinakiem ugotuj w dużej ilości osolonej wody (300 g ravioli) przez 4–5 minut. W międzyczasie roztop 100 g masła na patelni z 8 listkami szałwii, aż uwolni aromat. Wyławiaj ravioli łyżką cedzakową, przełóż na patelnię i delikatnie wymieszaj. Podawaj posypane 50 g tartego parmezanu."
  },
  21: {
    it: "Per i cannelloni ricotta e spinaci prepara il ripieno mescolando 300 g di ricotta ben scolata con 300 g di spinaci cotti e tritati, 1 uovo, 50 g di Parmigiano e noce moscata. Riempi 12 cannelloni con il composto e disponili in una teglia. Copri con 500 ml di salsa di pomodoro e 500 ml di besciamella, quindi spolvera con Parmigiano. Cuoci in forno a 180 °C per circa 30 minuti.",
    pl: "Do cannelloni z ricottą i szpinakiem przygotuj farsz, mieszając 300 g dobrze odsączonej ricotty z 300 g ugotowanego i posiekanego szpinaku, 1 jajkiem, 50 g parmezanu i szczyptą gałki muszkatołowej. Napełnij 12 rurek cannelloni farszem i ułóż je w naczyniu żaroodpornym. Polej 500 ml sosu pomidorowego i 500 ml beszamelu, posyp parmezanem. Piecz w 180 °C około 30 minut."
  },
  22: {
    it: "Per gli gnocchi di patate fai bollire 1 kg di patate con la buccia fino a cottura, pelale e schiacciale ancora calde. Aggiungi 300 g di farina 00 e 1 uovo, impastando velocemente fino a ottenere un composto omogeneo. Forma dei cordoncini, taglia gli gnocchi e passali sui rebbi di una forchetta. Cuocili in acqua bollente salata: quando salgono a galla, scolali e condiscili con 500 g di salsa di pomodoro, basilico e Parmigiano.",
    pl: "Gnocchi ziemniaczane przygotuj, gotując 1 kg ziemniaków w mundurkach, obierz je i jeszcze ciepłe przeciśnij przez praskę. Dodaj 300 g mąki i 1 jajko, szybko zagnieć gładkie ciasto. Uformuj wałki, pokrój na kluski i zroluj na widelcu. Gotuj w osolonej wodzie, aż wypłyną, odcedź i podawaj z 500 g sosu pomidorowego, bazylią i parmezanem."
  },
  23: {
    it: "Per le orecchiette con cime di rapa pulisci 500 g di cime di rapa eliminando le parti dure. Sbollentale per 5 minuti in acqua salata, poi scolale con una schiumarola e conserva l’acqua. Nella stessa acqua cuoci 400 g di orecchiette. In una padella scalda 3 cucchiai di olio con 2 spicchi d’aglio, 4 filetti di acciuga e peperoncino. Aggiungi le cime di rapa lessate e fai insaporire. Scola le orecchiette e saltale con le verdure. Servi con olio a crudo.",
    pl: "Do orecchiette con cime di rapa oczyść 500 g liści rzepy (brokuł liściowy), usuwając twarde części. Blanszuj je 5 minut w osolonej wodzie, odcedź łyżką cedzakową, a wodę pozostaw. W tej samej wodzie ugotuj 400 g makaronu orecchiette. Na patelni rozgrzej 3 łyżki oliwy z 2 ząbkami czosnku, 4 filetami anchois i szczyptą chili. Dodaj blanszowane liście i podsmaż. Odcedź orecchiette i wymieszaj z warzywami. Skrop oliwą."
  },
  24: {
    it: "Per il risotto alla Milanese fai tostare mezza cipolla tritata in 40 g di burro e, se vuoi essere tradizionale, 20 g di midollo di vitello. Aggiungi 320 g di riso Carnaroli e tostalo. Sfuma con 100 ml di vino bianco. Sciogli alcuni pistilli di zafferano in poco brodo caldo e aggiungili al risotto. Versa poco alla volta circa 1 l di brodo bollente, mescolando continuamente, fino a cottura al dente. Manteca con 40 g di burro e 80 g di Parmigiano.",
    pl: "Do risotto alla Milanese podsmaż posiekaną małą cebulę na 40 g masła i, dla tradycji, 20 g szpiku cielęcego. Dodaj 320 g ryżu Carnaroli i praż, następnie wlej 100 ml białego wina. Rozpuść kilka nitek szafranu w odrobinie gorącego bulionu i dodaj do ryżu. Dolewaj porcjami około 1 l gorącego bulionu, cały czas mieszając, aż ryż będzie al dente. Zakończ, dodając 40 g masła i 80 g parmezanu, energicznie mieszając."
  },
  25: {
    it: "Per il risotto ai funghi porcini reidrata 300 g di porcini secchi o pulisci quelli freschi e affettali. Soffriggi una cipolla tritata in 50 g di burro, aggiungi 320 g di riso e tostalo. Sfuma con 100 ml di vino bianco. Aggiungi i funghi e poi versa poco alla volta 1 l di brodo vegetale caldo, mescolando. Quando il riso è al dente, manteca con 50 g di burro e 50 g di Parmigiano grattugiato.",
    pl: "Do risotto ai funghi porcini namocz 300 g suszonych prawdziwków lub oczyść świeże i pokrój. Podsmaż posiekaną cebulę na 50 g masła, dodaj 320 g ryżu i praż, wlej 100 ml białego wina. Dodaj grzyby, następnie wlewaj po trochu 1 l gorącego bulionu warzywnego, mieszając. Gdy ryż będzie al dente, wmieszaj 50 g masła i 50 g tartego parmezanu."
  },
  26: {
    it: "Per il risotto al nero di seppia pulisci 500 g di seppie e tagliale a striscioline. In una casseruola soffriggi una cipolla tritata e 2 spicchi d’aglio in olio. Aggiungi le seppie e rosola, poi unisci 320 g di riso e tostalo. Sfuma con un bicchiere di vino bianco. Sciogli 2 bustine di nero di seppia in un po’ di brodo di pesce caldo e aggiungi al riso. Versa a poco a poco circa 1 l di brodo di pesce, mescolando finché il riso è al dente. Manteca con 30 g di burro e 50 g di Parmigiano.",
    pl: "Do risotto al nero di seppia oczyść 500 g kałamarnic i pokrój je w paski. W garnku podsmaż posiekaną cebulę i 2 ząbki czosnku na oliwie, dodaj kałamarnice i obsmaż, następnie wsyp 320 g ryżu i zrumień. Wlej kieliszek białego wina. Rozpuść 2 saszetki atramentu z sepii w odrobinie gorącego bulionu rybnego i wlej do ryżu. Dolewaj stopniowo około 1 l bulionu, mieszając, aż ryż będzie al dente. Na końcu dodaj 30 g masła i 50 g parmezanu."
  },
  27: {
    it: "Il risotto allo zafferano segue la stessa preparazione di quello milanese: tosta 320 g di riso in burro con cipolla, sfuma con vino bianco e cuoci aggiungendo gradualmente 1 l di brodo. A metà cottura sciogli lo zafferano in poco brodo e incorporalo. Manteca con burro e Parmigiano a fine cottura.",
    pl: "Risotto allo zafferano przygotowuje się jak alla Milanese: podsmaż 320 g ryżu na maśle z cebulą, wlej białe wino i gotuj, dodając stopniowo 1 l bulionu. W połowie gotowania rozpuść szafran w odrobinie bulionu i dolej do ryżu. Na końcu wymieszaj z masłem i parmezanem."
  },
  28: {
    it: "Per il risotto ai frutti di mare pulisci 1 kg di cozze, vongole, gamberi e calamari. Apri cozze e vongole in una padella con coperchio e conserva il liquido filtrato. In una casseruola soffriggi una cipolla e uno spicchio d’aglio in olio, aggiungi 320 g di riso e tostalo. Sfuma con 100 ml di vino bianco. Versa gradualmente 1 l di brodo di pesce caldo e il liquido dei molluschi, mescolando. A metà cottura aggiungi 2 pomodori pelati tritati e i calamari a rondelle; poco prima della fine incorpora gamberi e molluschi sgusciati. Completa con prezzemolo.",
    pl: "Do risotto ai frutti di mare oczyść 1 kg muli, małży, krewetek i kalmarów. Otwórz małże i mule pod przykryciem na patelni, zachowaj odcedzony płyn. W garnku podsmaż cebulę i ząbek czosnku na oliwie, wsyp 320 g ryżu i zrumień. Wlej 100 ml białego wina. Stopniowo dolewaj 1 l gorącego bulionu rybnego i płyn z małży, mieszając. W połowie gotowania dodaj 2 posiekane pomidory i pokrojone kalmary; pod koniec wrzuć obrane krewetki i małże. Posyp natką pietruszki."
  },
  29: {
    it: "Per il risotto agli asparagi pulisci 500 g di asparagi eliminando la parte dura e separa le punte dai gambi. Taglia i gambi a rondelle e cuocili in 1 l di brodo vegetale per 10 minuti, poi frulla per ottenere una crema. In una casseruola soffriggi una cipolla in 40 g di burro, aggiungi 320 g di riso e tostalo. Sfuma con 100 ml di vino bianco, quindi aggiungi gradualmente il brodo agli asparagi e la crema ottenuta. A metà cottura unisci le punte di asparagi. Manteca con 50 g di burro e 50 g di Parmigiano.",
    pl: "Do risotto agli asparagi oczyść 500 g szparagów, odcinając twarde końce, oddziel czubki od łodyg. Pokrój łodygi na plasterki i gotuj przez 10 minut w 1 l bulionu warzywnego, następnie zmiksuj na krem. W garnku podsmaż cebulę na 40 g masła, dodaj 320 g ryżu i zrumień. Wlej 100 ml białego wina, następnie stopniowo dodawaj bulion ze szparagami i uzyskany krem. W połowie gotowania dodaj czubki szparagów. Na końcu wmieszaj 50 g masła i 50 g parmezanu."
  },
  30: {
    it: "Per il risotto alla zucca taglia 500 g di polpa di zucca a cubetti e fallo stufare con una cipolla tritata in 2 cucchiai di olio finché sarà morbida. Aggiungi 320 g di riso e tostalo, poi sfuma con 100 ml di vino bianco. Unisci gradualmente 1 l di brodo vegetale, mescolando. Quando il riso è quasi cotto, schiaccia la zucca con una forchetta e incorpora alla crema di riso. Manteca con 50 g di burro e 50 g di Parmigiano e profuma con rosmarino.",
    pl: "Do risotto alla zucca pokrój 500 g miąższu dyni w kostkę i duś z posiekaną cebulą na 2 łyżkach oliwy, aż zmięknie. Dodaj 320 g ryżu i podsmaż, następnie wlej 100 ml białego wina. Stopniowo wlewaj 1 l bulionu warzywnego, mieszając. Gdy ryż będzie prawie ugotowany, rozgnieć dynię widelcem i dodaj do ryżu. Pod koniec wmieszaj 50 g masła i 50 g parmezanu, dopraw rozmarynem."
  },
  31: {
    it: "La ribollita toscana richiede tempo: ammolla 300 g di fagioli cannellini per una notte e lessali. In una grande pentola soffriggi una cipolla, due carote, due coste di sedano e una foglia di cavolo nero tritati in olio. Aggiungi 3 patate a dadini, 400 g di pomodori pelati e i fagioli cotti con il loro brodo (circa 1 l). Unisci 300 g di pane raffermo a pezzi e cuoci a fuoco basso per almeno un’ora, mescolando spesso. Lascia riposare e riscalda nuovamente il giorno dopo (da qui il nome ribollita). Servi con olio d’oliva.",
    pl: "Ribollita toskańska wymaga czasu: namocz 300 g fasoli cannellini przez noc i ugotuj. W dużym garnku podsmaż na oliwie posiekaną cebulę, dwie marchewki, dwie łodygi selera i garść posiekanego jarmużu. Dodaj 3 ziemniaki pokrojone w kostkę, 400 g pomidorów pelati i ugotowaną fasolę wraz z ok. 1 l bulionu. Wrzuć 300 g czerstwego chleba pokrojonego na kawałki i gotuj na małym ogniu co najmniej godzinę, często mieszając. Odstaw i odgrzej następnego dnia (stąd nazwa ribollita). Podawaj skropione oliwą."
  },
  32: {
    it: "Per la zuppa di lenticchie sciacqua 300 g di lenticchie e mettile a cuocere con una cipolla tritata, una carota e una costa di sedano in olio. Aggiungi 2 spicchi d’aglio, 400 g di pomodori pelati e 1 foglia di alloro. Copri con 1 l di brodo o acqua e cuoci a fuoco basso per 40 minuti o fino a che le lenticchie sono morbide. Regola di sale e pepe, elimina l’alloro e servi con un filo di olio e pane.",
    pl: "Do zupy z soczewicy opłucz 300 g soczewicy i gotuj ją z posiekaną cebulą, marchewką i selerem na oliwie. Dodaj 2 ząbki czosнku, 400 g pomidorów pelati i liść laurowy. Zalej 1 l bulionu lub wody i gotuj na małym ogniu przez ok. 40 minut, aż soczewica zmięknie. Dopraw solą i pieprzem, usuń liść laurowy i podawaj z oliwą i pieczywem."
  },
  33: {
    it: "Il minestrone è una densa minestra di verdure. Taglia a cubetti 2 carote, 2 zucchine, una patata, una costa di sedano, un porro e una cipolla. In una pentola capiente soffriggi la cipolla e il sedano in olio, poi aggiungi le altre verdure, 100 g di fagioli borlotti cotti e 2 pomodori pelati a pezzi. Copri con 1,5 l di brodo vegetale e cuoci per 30 minuti. Aggiungi 100 g di pasta corta e cuoci finché è tenera. Servi con Parmigiano.",
    pl: "Minestrone to gęsta zupa z warzyw. Pokrój w kostkę 2 marchewki, 2 cukinie, ziemniaka, łodygę selera, pora i cebulę. W dużym garnku podsmaż cebulę i seler na oliwie, następnie dodaj pozostałe warzywa, 100 g ugotowanej fasoli borlotti i 2 pomidory pelati w kawałkach. Zalej 1,5 l bulionu warzywnego i gotuj 30 minut. Dodaj 100 g drobnego makaronu i gotuj, aż będzie miękki. Podawaj z parmezanem."
  },
  34: {
    it: "Per l’acquacotta soffriggi 2 cipolle e 2 coste di sedano tritati in olio. Aggiungi 500 g di pomodori pelati spezzettati e cuoci per 20 minuti. Versa 1 l di acqua o brodo e porta a ebollizione. Rompi 4 uova una alla volta direttamente nella zuppa e cuoci finché l’albume si rapprende. Adagia una fetta di pane raffermo in ciascun piatto e versa sopra la zuppa con l’uovo. Completa con basilico e olio.",
    pl: "Do zupy acquacotta podsmaż 2 posiekane cebule i 2 łodygi selera na oliwie. Dodaj 500 g pomidorów pelati w kawałkach i gotuj 20 minut. Wlej 1 l wody lub bulionu i zagotuj. Wbijaj po jednym 4 jajka prosto do zupy i gotuj, aż białko się zetnie. Do każdej miski włóż kromkę czerstwego chleba i zalej zupą z jajkiem. Na wierzch daj bazylię i skrop oliwą."
  },
  35: {
    it: "Per la zuppa di verdure fai soffriggere una cipolla e una carota tritate in olio, aggiungi 2 patate a cubetti, 2 zucchine, una manciata di fagiolini e 2 pomodori a pezzi. Copri con 1 l di brodo vegetale e cuoci finché le verdure sono morbide. Regola di sale e pepe. Servi con un filo d’olio e Parmigiano.",
    pl: "Do zupy warzywnej podsmaż na oliwie posiekaną cebulę i marchewkę, dodaj 2 ziemniaki w kostkę, 2 cukinie, garść fasolki szparagowej i 2 pokrojone pomidory. Zalej 1 l bulionu warzywnego i gotuj, aż warzywa zmiękną. Dopraw solą i pieprzem. Podawaj skropione oliwą i posypane parmezanem."
  },
  36: {
    it: "Prepara la polenta portando a ebollizione 1,5 l di acqua salata e versando a pioggia 400 g di farina di mais, mescolando continuamente per evitare grumi. Cuoci per circa 40 minuti finché è densa. In un’altra padella rosola una cipolla con 500 g di salsiccia sbriciolata, aggiungi 400 g di passata di pomodoro e cuoci finché il sugo si addensa. Servi la polenta morbida condita con il ragù di salsiccia e Parmigiano.",
    pl: "Przygotuj polentę, doprowadzając do wrzenia 1,5 l osolonej wody i wsypując powoli 400 g mąki kukurydzianej, cały czas mieszając, by nie utworzyły się grudki. Gotuj ok. 40 minut, aż masa zgęstnieje. Na innej patelni podsmaż cebulę z 500 g pokruszonej kiełbasy, dodaj 400 g passaty pomidorowej i gotuj, aż sos zgęstnieje. Podawaj miękką polentę z sosem kiełbasianym i parmezanem."
  },
  37: {
    it: "Per l’ossobuco alla Milanese infarina 4 ossibuchi di vitello e rosolali in 50 g di burro finché sono dorati. Toglili e, nella stessa casseruola, soffriggi una cipolla, una carota e una costa di sedano tritati. Rimetti gli ossibuchi, sfuma con 200 ml di vino bianco e aggiungi 500 ml di brodo e 2 cucchiai di concentrato di pomodoro. Copri e cuoci per circa 1 ora e mezzo a fuoco basso, finché la carne è tenera. Prepara una gremolada tritando prezzemolo, aglio e scorza di limone e aggiungila al piatto prima di servire, insieme a risotto. ",
    pl: "Do ossobuco alla Milanese obtocz 4 plastry giczy cielęcej w mące i obsmaż na 50 g masła, aż się zrumienią. Odłóż je, a w tym samym garnku podsmaż posiekaną cebulę, marchewkę i łodygę selera. Włóż z powrotem ossobuco, wlej 200 ml białego wina i dodaj 500 ml bulionu oraz 2 łyżki koncentratu pomidorowego. Przykryj i duś ok. 1,5 godziny na małym ogniu, aż mięso będzie miękkie. Przygotuj gremolatę, siekając pietruszkę, czosnek i skórkę z cytryny, i posyp nią danie tuż przed podaniem z risotto."
  },
  38: {
    it: "Per i saltimbocca alla romana adagia su 8 fettine sottili di vitello una foglia di salvia e una fetta di prosciutto crudo, fermandole con uno stuzzicadenti. In una padella sciogli 50 g di burro e cuoci le fettine per pochi minuti per lato. Sfuma con 100 ml di vino bianco, fai restringere il fondo e servi i saltimbocca nappando con il sughetto.",
    pl: "Do saltimbocca alla romana nałóż na 8 cienkich plastrów cielęciny listki szałwii i plastry szynki parmeńskiej, zabezpiecz wykałaczką. Na patelni rozpuść 50 g masła i smaż mięso po kilka minut z każdej strony. Podlej 100 ml białego wina, zredukuj sos i polej nim saltimbocca przed podaniem."
  },
  39: {
    it: "Per le scaloppine al limone infarina 4 fettine di vitello e rosolale in 50 g di burro. Toglile, deglassa la padella con 100 ml di vino bianco, aggiungi il succo di 2 limoni e 250 ml di brodo e fai ridurre. Rimetti la carne nella salsa per un minuto. Servi con fettine di limone e prezzemolo.",
    pl: "Do scaloppine al limone obtocz 4 plastry cielęciny w mące i obsmaż na 50 g masła. Wyjmij, a patelnię zdeglazuj 100 ml białego wina, dodaj sok z 2 cytryn i 250 ml bulionu, zredukuj sos. Włóż mięso z powrotem na minutę. Podawaj z plasterkami cytryny i natką pietruszki."
  },
  40: {
    it: "Per l’arrosto di maiale massaggia 1 kg di lonza con 2 spicchi d’aglio schiacciati, sale, pepe e rosmarino. Rosolala in una casseruola con olio, poi sfuma con 100 ml di vino bianco. Trasferisci la carne in forno preriscaldato a 180 °C e cuoci per circa 1 ora, bagnando di tanto in tanto con il fondo di cottura. Fai riposare prima di affettare.",
    pl: "Aby przygotować pieczeń wieprzową, natrzyj 1 kg schabu 2 zgniecionymi ząbkami czosnku, solą, pieprzem i rozmarynem. Obsmaż mięso w brytfannie na oliwie, podlej 100 ml białego wina. Przełóż do piekarnika nagrzanego do 180 °C i piecz około godziny, co jakiś czas polewając sosem. Odstaw przed krojeniem."
  },
  41: {
    it: "Per la cotoletta alla milanese batti leggermente 4 costolette di vitello con l’osso. Passale nella farina, poi in 2 uova sbattute e infine in abbondante pangrattato pressandolo bene. Friggi le cotolette in burro chiarificato o olio di arachidi a 170 °C fino a doratura su entrambi i lati. Scolale su carta e servi con spicchi di limone.",
    pl: "Kotlet po mediolańsku przygotuj, lekko rozbijając 4 kotlety cielęce z kością. Obtacz je w mące, następnie w 2 roztrzepanych jajach i w grubiej bułce tartej, dobrze dociskając. Smaż na klarowanym maśle lub oleju arachidowym w temperaturze ok. 170 °C, aż będą złote z obu stron. Odsącz na papierze i podawaj z cząstkami cytryny."
  },
  42: {
    it: "Per il pollo alla cacciatora rosola 1,5 kg di pollo a pezzi in olio, quindi toglilo. Nella stessa casseruola soffriggi una cipolla, 2 spicchi d’aglio, 2 carote e una costa di sedano tritati. Rimetti il pollo, sfuma con 200 ml di vino rosso, aggiungi 400 g di pomodori pelati, un rametto di rosmarino e qualche oliva nera. Cuoci coperto per circa 40 minuti finché il pollo è tenero.",
    pl: "Do pollo alla cacciatora podsmaż 1,5 kg kurczaka w kawałkach na oliwie, a następnie odłóż. W tym samym garnku podsmaż posiekaną cebulę, 2 ząbki czosnku, 2 marchewki i łodygę selera. Włóż z powrotem kurczaka, wlej 200 ml czerwonego wina, dodaj 400 g pomidorów pelati, gałązkę rozmarynu i kilka czarnych oliwek. Duś pod przykryciem ok. 40 minut, aż mięso będzie miękkie."
  },
  43: {
    it: "Per il brasato al Barolo metti a marinare 1,5 kg di carne di manzo in una bottiglia di vino Barolo con una cipolla, una carota, un gambo di sedano, 2 chiodi di garofano e 2 foglie d’alloro per 12 ore. Scola la carne e asciugala, filtrando la marinata. Rosola la carne in 50 g di burro e olio, aggiungi le verdure della marinata e sfuma con la marinata filtrata. Cuoci coperto a fuoco bassissimo per 2 – 3 ore finché la carne è tenera. Frulla il sugo, affetta la carne e servila con la salsa.",
    pl: "Do brasato al Barolo zamarynuj 1,5 kg wołowiny w butelce wina Barolo z cebulą, marchewką, łodygą selera, 2 goździkami i 2 liśćmi laurowymi przez 12 godzin. Wyjmij mięso, osusz, a marynatę odcedź. Obsmaż mięso na 50 g masła z oliwą, dodaj warzywa z marynaty i podlej odcedzonym winem. Duś pod przykryciem na bardzo małym ogniu 2–3 godziny, aż mięso będzie miękkie. Zmiksuj sos, pokrój mięso w plastry i podawaj z sosem."
  },
  44: {
    it: "Per lo spezzatino taglia 800 g di manzo a cubi. Rosola la carne in olio e toglila. Nella stessa casseruola soffriggi una cipolla, 2 carote e 2 coste di sedano tritati. Rimetti la carne, aggiungi un rametto di rosmarino, sfuma con 200 ml di vino rosso e aggiungi 400 g di pomodori pelati e brodo quanto basta per coprire. Cuoci a fuoco lento per 2 ore finché la carne è tenera. Servi con polenta.",
    pl: "Do spezzatino (gulaszu) pokrój 800 g wołowiny w kostkę. Obsmaż mięso na oliwie i odłóż. W tym samym garnku podsmaż posiekaną cebulę, 2 marchewki i 2 łodygi selera. Włóż mięso z powrotem, dodaj gałązkę rozmarynu, wlej 200 ml czerwonego wina i dodaj 400 g pomidorów pelati oraz tyle bulionu, aby przykryło mięso. Duś na wolnym ogniu 2 godziny, aż mięso zmięknie. Podawaj z polentą."
  },
  45: {
    it: "Per il cacciucco, una zuppa di pesce livornese, pulisci 1 kg di pesci misti (polpo, seppie, scorfano, triglie), cozze e gamberi. In una casseruola soffriggi 4 spicchi d’aglio e un peperoncino in olio, aggiungi 1 cipolla tritata e 700 g di pomodori pelati. Unisci i pezzi di pesce più duri (polpo e seppie) e cuoci per 20 minuti, poi aggiungi gli altri pesci e, infine, i crostacei. Versa 500 ml di brodo di pesce o acqua e cuoci finché tutto è tenero. Servi il cacciucco su fette di pane tostato strofinate con aglio.",
    pl: "Do cacciucco, livornijskiej zupy rybnej, oczyść 1 kg mieszanych ryb (ośmiornica, mątwy, skorpena, czerwone mulaki), małże i krewetki. W dużym garnku podsmaż 4 ząbki czosнku i papryczkę chili na oliwie, dodaj posiekaną cebulę i 700 g pomidorów pelati. Dodaj kawałki twardszych ryb (ośmiornicy i mątw) i gotuj 20 minut, następnie dodaj pozostałe ryby, a na końcu skorupiaki. Wlej 500 ml bulionu rybnego lub wody i gotuj, aż wszystko będzie miękkie. Podawaj cacciucco na kromkach opiekanego chleba natartego czosnkiem."
  },
  46: {
    it: "Per la zuppa di pesce utilizza circa 800 g di pesci e crostacei misti. In una casseruola soffriggi una cipolla, un gambo di sedano e uno spicchio d’aglio in olio. Aggiungi 700 g di pomodori pelati e 1 l di brodo di pesce. Unisci prima i pesci a carne soda (tranci di coda di rospo, gallinella), poi dopo 15 minuti i pesci più delicati (orata, merluzzo) e infine i crostacei. Cuoci finché il pesce è cotto. Servi la zuppa con pane tostato.",
    pl: "Do zupy rybnej użyj około 800 g różnych ryb i skorupiaków. W garnku podsmaż cebulę, łodygę selera i ząbek czosнku na oliwie. Dodaj 700 g pomidorów pelati i 1 l bulionu rybnego. Najpierw włóż ryby o jędrnym mięsie (ogoniast, kurkę), po 15 minutach delikatniejsze (dorada, dorsz), a na końcu skorupiaki. Gotuj, aż ryby będą ugotowane. Podawaj zupę z grzankami."
  },
  47: {
    it: "Per il baccalà alla Vicentina lascia in ammollo 800 g di baccalà salato per 2 giorni cambiando spesso l’acqua. Scolalo, elimina pelle e spine e taglialo a pezzi. In un tegame soffriggi 2 cipolle affettate in olio e aggiungi 4 filetti di acciuga. Disponi i pezzi di baccalà sopra il soffritto, cospargi con 50 g di Parmigiano grattugiato e copri con 500 ml di latte e 100 ml di olio. Cuoci a fuoco dolcissimo per circa 4 ore senza mescolare (muovi solo il tegame). Servi con polenta.",
    pl: "Do baccalà alla Vicentina namocz 800 g solonego dorsza przez 2 dni, często zmieniając wodę. Osusz, usuń skórę i ości i pokrój na kawałki. W rondlu podsmaż 2 pokrojone cebule na oliwie, dodaj 4 filety anchois. Na warstwie cebuli ułóż kawałki dorsza, posyp 50 g tartego parmezanu i zalej 500 ml mleka oraz 100 ml oliwy. Gotuj na bardzo małym ogniu przez około 4 godziny, nie mieszając (tylko potrząsając garnkiem). Podawaj z polentą."
  },
  48: {
    it: "Per il polpo alla luciana pulisci 1 kg di polpo eliminando becco e occhi. Mettilo in una pentola con 400 g di pomodori pelati, 2 spicchi d’aglio, un peperoncino, una manciata di olive nere e capperi dissalati. Copri e cuoci a fuoco basso per 50–60 minuti, senza aggiungere acqua: il polpo cuocerà nei suoi succhi. Cospargi con prezzemolo tritato e servi con pane tostato.",
    pl: "Do polpo alla luciana oczyść 1 kg ośmiornicy, usuwając dziób i oczy. Włóż ją do garnka z 400 g pomidorów pelati, 2 ząbkami czosнku, papryczką chili, garścią czarnych oliwek i odsączonych kaparów. Przykryj i gotuj na małym ogniu przez 50–60 minut bez dodawania wody – ośmiornica puści własny sok. Posyp posiekaną pietruszką i podawaj z grzankami."
  },
  49: {
    it: "Per gli involtini di vitello stendi 8 fettine sottili di vitello, adagia su ciascuna una fetta di prosciutto e una di formaggio (provola o scamorza) e una foglia di salvia. Arrotola e fissa con stuzzicadenti. Rosola gli involtini in olio e burro, sfuma con 50 ml di vino bianco e cuoci per 10 minuti. Servi con il sughetto.",
    pl: "Do roladek z cielęciny rozłóż 8 cienkich plastrów cielęciny, ułóż na każdym plaster szynki i sera (provola lub scamorza) oraz liść szałwii. Zwiń i zabezpiecz wykałaczkami. Podsmaż roladki na maśle i oliwie, podlej 50 ml białego wina i duś około 10 minut. Podawaj z powstałym sosem."
  },
  50: {
    it: "Prosciutto e melone è un antipasto estivo: taglia a fette 1 melone maturo, elimina i semi e la scorza. Avvolgi ogni fetta con una fetta sottile di prosciutto crudo (circa 100 g in totale) e servi subito.",
    pl: "Prosciutto e melone to letnia przystawka: pokrój dojrzały melon w plastry, usuń skórkę i pestki. Owiń każdą cząstkę cienkim plasterkiem szynki parmeńskiej (łącznie ok. 100 g) i podawaj od razu."
  },
  51: {
    it: "Per il carpaccio di manzo congela leggermente 400 g di filetto di manzo per affettarlo più facilmente. Taglialo a fettine sottilissime e disponile su un piatto. Condisci con succo di limone, olio extravergine d’oliva, sale e pepe. Completa con rucola fresca e scaglie di Parmigiano.",
    pl: "Aby przygotować carpaccio di manzo, lekko zamroź 400 g polędwicy wołowej, aby łatwiej ją pokroić. Pokrój na bardzo cienkie plasterki i ułóż na talerzu. Skrop sokiem z cytryny i oliwą, posól i popieprz. Udekoruj rukolą i płatkami parmezanu."
  },
  52: {
    it: "Per il tiramisù separa 6 tuorli dagli albumi. Sbatti i tuorli con 100 g di zucchero fino a ottenere una crema chiara, poi incorpora 500 g di mascarpone. A parte monta gli albumi a neve e incorporali delicatamente. Prepara 300 ml di caffè espresso freddo e, se gradisci, aggiungi 30 ml di Marsala. Inzuppa velocemente 300 g di savoiardi nel caffè e disponili in una teglia. Copri con uno strato di crema, poi prosegui con un secondo strato di savoiardi inzuppati e termina con la crema. Metti in frigorifero almeno 4 ore. Prima di servire spolvera con cacao amaro.",
    pl: "Do tiramisù oddziel 6 żółtek od białek. Utrzyj żółtka z 100 g cukru na jasny krem, następnie dodaj 500 g mascarpone. Ubij osobno białka na sztywną pianę i delikatnie wmieszaj do kremu. Przygotuj 300 ml wystudzonego espresso i, jeśli lubisz, dodaj 30 ml Marsali. Szybko namaczaj 300 g biszkoptów savoiardi w kawie i układaj je w naczyniu. Rozsmaruj warstwę kremu, ułóż kolejną warstwę namoczonych biszkoptów i zakończ kremem. Wstaw do lodówki na co najmniej 4 godziny. Przed podaniem posyp kakao."
  },
  53: {
    it: "Per la panna cotta porta quasi a bollore 500 ml di panna con 50 g di zucchero e una bacca di vaniglia incisa. Nel frattempo ammolla 8 g di gelatina in fogli in acqua fredda. Quando la panna è calda, spegni il fuoco, elimina la vaniglia e sciogli la gelatina ben strizzata. Versa negli stampini e fai raffreddare in frigorifero per almeno 4 ore. Servi con salsa ai frutti di bosco.",
    pl: "Do panna cotta podgrzej prawie do wrzenia 500 ml śmietanki z 50 g cukru i przekrojoną laską wanilii. W międzyczasie namocz 8 g żelatyny w zimnej wodzie. Gdy śmietanka jest gorąca, wyjmij wanilię i rozpuść odciśniętą żelatynę. Wlej do foremek i schładzaj w lodówce co najmniej 4 godziny. Podawaj z sosem z owoców leśnych."
  },
  54: {
    it: "Per i cannoli siciliani prepara le cialde mescolando 250 g di farina, 30 g di zucchero, 30 g di strutto, 30 g di burro, 1 uovo e 50 ml di Marsala; impasta e lascia riposare. Stendi l’impasto sottile, ritaglia dei dischi, avvolgili sui cannelli e friggi in olio caldo fino a doratura. Per il ripieno setaccia 500 g di ricotta di pecora, mescola con 200 g di zucchero a velo e aggiungi gocce di cioccolato e canditi a piacere. Farcisci le cialde fredde poco prima di servire e spolvera con zucchero a velo.",
    pl: "Aby zrobić cannoli siciliani, przygotuj skorupki, mieszając 250 g mąki, 30 g cukru, 30 g smalcu, 30 g masła, 1 jajko i 50 ml Marsali; zagnieć i odstaw. Rozwałkuj cienko ciasto, wytnij krążki, nawiń na metalowe rurki i smaż w oleju na złoto. Na nadzienie przetrzyj 500 g serka ricotta, wymieszaj z 200 g cukru pudru i dodaj krople czekolady i kandyzowaną skórkę. Nadziewaj ostudzone skorupki tuż przed podaniem i posyp cukrem pudrem."
  },
  55: {
    it: "Per il gelato alla vaniglia porta a quasi bollore 500 ml di latte con 250 ml di panna e i semi di una bacca di vaniglia. Sbatti 4 tuorli con 150 g di zucchero fino a ottenere un composto spumoso. Versa a filo il latte caldo sui tuorli mescolando, poi rimetti sul fuoco e cuoci a fiamma bassa fino a ottenere una crema inglese che veli il cucchiaio. Fai raffreddare, quindi manteca in gelatiera. Se non hai la gelatiera, congela la crema e mescola ogni 30 minuti per rompere i cristalli di ghiaccio.",
    pl: "Aby przygotować lody waniliowe, podgrzej prawie do wrzenia 500 ml mleka z 250 ml śmietanki i nasionkami z laski wanilii. Utrzyj 4 żółtka z 150 g cukru na puszystą masę. Powoli wlewaj gorące mleko do żółtek, mieszając, następnie przelej z powrotem do garnka i gotuj na małym ogniu, aż powstanie lekki krem, który oblepia łyżkę. Ostudzoną masę przelej do maszynki do lodów. Jeśli jej nie masz, wstaw do zamrażarki i mieszaj co 30 minut, aby rozbić kryształki lodu."
  },
  56: {
    it: "Per lo zabaglione monta a bagnomaria 4 tuorli con 100 g di zucchero finché diventano chiari. Continua a sbattere e aggiungi a filo 100 ml di Marsala o vino dolce. Cuoci a fuoco dolce sempre sbattendo fino a ottenere una crema gonfia e vellutata. Servi caldo o freddo, anche con biscotti.",
    pl: "Do zabaione ubij na parze 4 żółtka z 100 g cukru, aż staną się jasne. Ciągle ubijając, wlej 100 ml Marsali lub słodkiego wina. Gotuj na małym ogniu, cały czas mieszając, aż powstanie puszysty, aksamitny krem. Podawaj na ciepło lub zimno, np. z ciasteczkami."
  },
  57: {
    it: "Per la cassata siciliana prepara un pan di Spagna con 4 uova, 120 g di zucchero, 120 g di farina e cuocilo in una teglia rotonda. Taglia la torta a dischi e spennellali con bagna di liquore. Lavora 500 g di ricotta con 200 g di zucchero a velo e aggiungi canditi e gocce di cioccolato. Rivesti uno stampo con fette di pan di Spagna e marzapane verde, riempi con la crema di ricotta e copri con un disco di torta. Lascia riposare in frigo, poi sforma e glassa con zucchero a velo e decora con frutta candita.",
    pl: "Do cassaty sycylijskiej upiecz biszkopt z 4 jaj, 120 g cukru i 120 g mąki w okrągłej formie. Pokrój na krążki i nasącz likierem. Utrzyj 500 g ricotty z 200 g cukru pudru i dodaj kandyzowane owoce oraz krople czekolady. Wyłóż formę plastrami biszkoptu i zielonym marcepanem, napełnij kremem z ricotty i przykryj plackiem. Schłódź w lodówce, a potem wyjmij, polej lukrem i udekoruj kandyzowanymi owocami."
  },
  58: {
    it: "Il panettone richiede un impasto lievitato complesso: mescola 500 g di farina manitoba con 100 g di zucchero, 10 g di lievito di birra, 200 ml di acqua tiepida, 4 uova, 150 g di burro morbido e un pizzico di sale. Lavora fino a ottenere un impasto elastico, poi incorpora 150 g di uvetta e 100 g di scorze candite. Lascia lievitare per ore finché raddoppia, quindi trasferisci in uno stampo cilindrico alto. Fai lievitare di nuovo e cuoci a 180 °C per 45 – 50 minuti. Lascia raffreddare capovolto.",
    pl: "Panettone wymaga skomplikowanego ciasta drożdżowego: wymieszaj 500 g mąki manitoba z 100 g cukru, 10 g drożdży, 200 ml ciepłej wody, 4 jajkami, 150 g miękkiego masła i szczyptą soli. Wyrabiaj, aż ciasto będzie elastyczne, następnie dodaj 150 g rodzynek i 100 g kandyzowanej skórki. Odstaw do wyrastania, aż podwoi objętość, przełóż do wysokiej formy. Pozostaw do ponownego wyrośnięcia i piecz w 180 °C przez 45–50 minut. Studź do góry nogami."
  },
  59: {
    it: "Il pandoro è simile al panettone ma senza canditi. Prepara un lievitino con 50 ml di latte, 10 g di lievito e 50 g di farina. Una volta lievitato, impasta con 500 g di farina, 200 g di zucchero, 4 uova, 200 g di burro morbido, la scorza di un limone e una bustina di vanillina. Fai lievitare l’impasto e poi mettilo in uno stampo a stella. Lascia lievitare di nuovo finché raggiunge il bordo e cuoci in forno a 170 °C per 50 minuti. Cospargi con zucchero a velo.",
    pl: "Pandoro przypomina panettone, ale bez kandyzowanej skórki. Zrób zaczyn z 50 ml mleka, 10 g drożdży i 50 g mąki. Po wyrośnięciu zagnieć z 500 g mąki, 200 g cukru, 4 jajkami, 200 g miękkiego masła, skórką z cytryny i opakowaniem wanilii. Pozwól ciastu wyrosnąć, następnie przełóż do gwiaździstej formy. Ponownie odstaw do wyrośnięcia, aż dosięgnie brzegu formy, i piecz w 170 °C przez 50 minut. Posyp cukrem pudrem."
  },
  60: {
    it: "Per le zeppole di San Giuseppe prepara una pasta bigné portando a ebollizione 250 ml di acqua con 50 g di burro e un pizzico di sale. Aggiungi 150 g di farina in un colpo solo e mescola fino a ottenere una palla che si stacca dalle pareti. Fai raffreddare, poi incorpora 3 uova una alla volta. Forma delle ciambelle con un sac à poche e friggile in olio a 170 °C fino a doratura. Farcisci con crema pasticcera e decora con amarene.",
    pl: "Zeppole di San Giuseppe to smażone ciastka z ciasta ptysiowego. Doprowadź do wrzenia 250 ml wody z 50 g masła i szczyptą soli. Wsyp 150 g mąki i mieszaj, aż powstanie kula odchodząca od ścianek. Ostudź, a następnie dodawaj po 3 jajka, jedno po drugim. Za pomocą rękawa cukierniczego formuj okręgi i smaż w oleju o temperaturze 170 °C na złoto. Napełnij kremem budyniowym i udekoruj wiśniami z syropu."
  },
  61: {
    it: "Per la sfogliatella prepara la sfoglia impastando 250 g di farina con acqua e un pizzico di sale, quindi stendila sottilissima, ungila con strutto e arrotolala per ottenere molti strati. Per il ripieno cuoci 200 g di semolino in latte, poi mescola con 250 g di ricotta, 150 g di zucchero, canditi tritati e un pizzico di cannella. Taglia il rotolo di sfoglia a fette, forma dei coni e riempili con la crema. Cuoci in forno a 200 °C finché sono dorate.",
    pl: "Sfogliatella wymaga cienkiego, wielowarstwowego ciasta: zagnieć 250 g mąki z wodą i szczyptą soli, rozwałkuj bardzo cienko, posmaruj smalcem i zroluj, aby uzyskać wiele warstw. Na nadzienie ugotuj 200 g kaszy manny w mleku, następnie wymieszaj z 250 g ricotty, 150 g cukru, posiekanymi kandyzowanymi skórkami i szczyptą cynamonu. Pokrój rulon ciasta na plastry, uformuj stożki i wypełnij kremem. Piecz w 200 °C, aż będą złote."
  },
  62: {
    it: "Per il babà al rum prepara un impasto con 500 g di farina, 3 uova, 20 g di lievito di birra, 70 g di burro, 50 g di zucchero e 150 ml di latte. Lascia lievitare, poi riempi gli stampini a metà e fai lievitare di nuovo fino al bordo. Cuoci a 180 °C per 25 minuti. Prepara uno sciroppo facendo bollire 500 ml d’acqua con 300 g di zucchero e 200 ml di rum; immergi i babà tiepidi nello sciroppo fino a che saranno imbevuti. Servi con panna montata.",
    pl: "Do babà al rum zrób ciasto z 500 g mąki, 3 jaj, 20 g drożdży, 70 g masła, 50 g cukru i 150 ml mleka. Odstaw do wyrośnięcia, następnie napełnij foremki do połowy i pozwól ciastu wyrosnąć do brzegów. Piecz w 180 °C przez 25 minut. Przygotuj syrop, gotując 500 ml wody z 300 g cukru i 200 ml rumu; zanurz ciepłe babki w syropie, aż nasiąkną. Podawaj z bitą śmietaną."
  },
  63: {
    it: "Per gli amaretti mescola 200 g di farina di mandorle con 200 g di zucchero a velo e 2 albumi montati a neve. Aggiungi qualche goccia di essenza di mandorla. Forma delle palline e passale nello zucchero semolato. Cuoci in forno a 170 °C per 15 minuti finché sono dorati.",
    pl: "Aby przygotować amaretti, wymieszaj 200 g mielonych migdałów z 200 g cukru pudru i 2 ubitymi na sztywno białkami. Dodaj kilka kropli aromatu migdałowego. Formuj kulki, obtaczaj w cukrze kryszta�łu i piecz w 170 °C przez 15 minut, aż się zrumienią."
  },
  64: {
    it: "Per i cantucci mescola 500 g di farina con 250 g di zucchero, 3 uova, 200 g di mandorle non pelate e una bustina di lievito. Forma due filoncini e cuocili in forno a 180 °C per 20 minuti. Taglia a fette diagonali e rimetti in forno per altri 10 minuti per farli biscottare.",
    pl: "Do cantucci wymieszaj 500 g mąki z 250 g cukru, 3 jajami, 200 g nieobranych migdałów i łyżeczką proszku do pieczenia. Uformuj dwa wałki i piecz w 180 °C przez 20 minut. Pokrój ukośnie na plastry i ponownie wstaw do pieca na 10 minut, aby zrobiły się chrupiące."
  },
  65: {
    it: "Per il pasticciotto leccese prepara una pasta frolla con 400 g di farina, 200 g di burro e 200 g di zucchero, 2 uova e scorza di limone. Avvolgi e fai riposare. Prepara la crema pasticcera con 500 ml di latte, 4 tuorli, 120 g di zucchero, 40 g di farina e scorza di limone. Rivesti gli stampini con la frolla, riempi con la crema, chiudi con altra pasta e cuoci a 180 °C per 25 minuti.",
    pl: "Do pasticciotto leccese zrób kruche ciasto z 400 g mąki, 200 g masła, 200 g cukru, 2 jaj i skórki z cytryny; zawiń i schłódź. Przygotuj krem budyniowy z 500 ml mleka, 4 żółtek, 120 g cukru, 40 g mąki i skórki cytrynowej. Wyłóż foremki ciastem, napełnij kremem, przykryj kolejną warstwą ciasta i piecz w 180 °C przez 25 minut."
  },
  66: {
    it: "Per il semifreddo al caffè monta a neve 4 albumi con 100 g di zucchero. A parte monta 400 ml di panna. Prepara uno sciroppo portando a bollore 50 ml di acqua con 100 g di zucchero; aggiungi 2 tazzine di caffè espresso e lascia raffreddare. Amalgama delicatamente albumi, panna e sciroppo al caffè, versa in uno stampo e congela per almeno 4 ore.",
    pl: "Do semifreddo al caffè ubij na sztywno 4 białka z 100 g cukru. Osobno ubij 400 ml śmietanki. Przygotuj syrop, gotując 50 ml wody z 100 g cukru, następnie dodaj 2 filiżanki espresso i ostudź. Delikatnie połącz pianę z białek, śmietankę i syrop kawowy, przełóż do foremki i zamroź co najmniej 4 godziny."
  },
  67: {
    it: "Per gli struffoli impasta 500 g di farina con 4 uova, 100 g di zucchero, 50 g di burro, la scorza di un limone grattugiata e un cucchiaio di liquore. Forma dei rotolini, tagliali a pezzetti e friggili in olio caldo fino a doratura. Scolali e mescolali ancora caldi con 200 g di miele sciolto e decorazioni di zucchero. Disponili a piramide su un piatto.",
    pl: "Do struffoli zagnieć 500 g mąki z 4 jajami, 100 g cukru, 50 g masła, skórką otartą z cytryny i łyżką likieru. Uformuj cienkie wałki, pokrój na małe kawałki i smaż w gorącym oleju na złoto. Odsącz i jeszcze ciepłe wymieszaj z 200 g roztopionego miodu i kolorową posypką. Ułóż na talerzu w formie piramidy."
  },
  68: {
    it: "Per la colomba pasquale impasta 500 g di farina manitoba con 150 g di zucchero, 2 uova, 2 tuorli, 150 g di burro morbido, 20 g di lievito, 200 ml di latte tiepido, scorza d’arancia e vaniglia. Lavora fino a ottenere un impasto liscio, poi incorpora 150 g di canditi. Fai lievitare fino al raddoppio, metti nello stampo a forma di colomba e lascia lievitare di nuovo. Spalma la superficie con una glassa di albume, zucchero e mandorle e cuoci a 180 °C per 45 minuti.",
    pl: "Do colomba pasquale zagnieć 500 g mąki manitoba z 150 g cukru, 2 jajami, 2 żółtkami, 150 g miękkiego masła, 20 g drożdży, 200 ml ciepłego mleka, startą skórką z pomarańczy i wanilią. Wyrabiaj, aż uzyskasz gładkie ciasto, następnie dodaj 150 g kandyzowanych owoców. Odstaw do wyrośnięcia, przełóż do formy w kształcie gołębicy i ponownie pozwól wyrosnąć. Posmaruj wierzch glazurą z białka, cukru i migdałów i piecz w 180 °C przez 45 minut."
  },
  69: {
    it: "Per le sarde in saor infarina leggermente 500 g di sarde pulite e friggile in olio caldo finché sono dorate. In un’altra padella soffriggi 2 grosse cipolle affettate in olio, aggiungi 30 g di pinoli e 30 g di uvetta ammollata, sfuma con 100 ml di aceto di vino e lascia evaporare. Disponi le sarde fritte in un piatto fondo a strati alternati con il composto di cipolle. Lascia riposare in frigorifero per almeno 24 ore prima di servire.",
    pl: "Do sarde in saor lekko obtocz 500 g oczyszczonych sardynek w mące i usmaż na gorącym oleju na złoty kolor. Na innej patelni podsmaż 2 duże cebule pokrojone w plastry, dodaj 30 g orzeszków piniowych i 30 g namoczonych rodzynek, podlej 100 ml octu winnego i odparuj. Ułóż smażone sardynki w głębokim naczyniu, przekładając warstwami z cebulą. Odstaw w lodówce na co najmniej 24 godziny przed podaniem."
  },
  70: {
    it: "Per il fritto misto di pesce utilizza 800 g di piccoli pesci, calamari e gamberi. Pulisci e asciuga bene il pesce, infarinalo leggermente e friggi in olio di semi a 170 °C in piccole quantità finché diventa dorato e croccante. Scolalo su carta assorbente e sala a piacere. Servi con spicchi di limone.",
    pl: "Do fritto misto di pesce użyj 800 g małych ryb, kalmarów i krewetek. Oczyść i dokładnie osusz ryby, lekko je oprósz mąką i smaż partiami w oleju o temperaturze 170 °C, aż będą złociste i chrupiące. Odsącz na papierowym ręczniku, posól do smaku i podawaj z ćwiartkami cytryny."
  },
  71: {
    it: "Per i gamberi alla Busara scotta 1 kg di gamberi interi in olio con una cipolla tritata, 2 spicchi d’aglio e un peperoncino. Sfuma con 50 ml di cognac o grappa, poi aggiungi 400 g di pomodori pelati a pezzi e un bicchiere di vino bianco. Copri e cuoci per 10 minuti. Completa con prezzemolo tritato e servi i gamberi con il loro sugo accompagnati da pane.",
    pl: "Do gamberi alla Busara podsmaż 1 kg całych krewetek na oliwie z posiekaną cebulą, 2 ząbkami czosнku i papryczką chili. Podlej 50 ml koniaku lub grappy, następnie dodaj 400 g pomidorów pelati w kawałkach i szklankę białego wina. Przykryj i gotuj 10 minut. Posyp posiekaną pietruszką i podawaj krewetki z sosem i pieczywem."
  }
};